apiVersion: v1  # API version for PersistentVolume
kind: PersistentVolume  # Indicates this is a PersistentVolume resource
metadata:
  name: mongo-pv  # Name of the PersistentVolume
  labels:
    type: local  # Label to identify the volume type
spec:
  storageClassName: manual  # StorageClass used for provisioning
  capacity:
    storage: 1Gi  # Size of the storage allocated
  accessModes:
    - ReadWriteOnce  # Volume can be mounted with read-write access by a single node
  hostPath:
    path: "/mnt/data/mongo"  # Path on the host where data is stored

---
apiVersion: v1  # API version for PersistentVolumeClaim
kind: PersistentVolumeClaim  # Indicates this is a PersistentVolumeClaim resource
metadata:
  name: mongo-pvc  # Name of the PersistentVolumeClaim
spec:
  storageClassName: manual  # StorageClass used for provisioning
  accessModes:
    - ReadWriteOnce  # Volume can be mounted with read-write access by a single node
  resources:
    requests:
      storage: 1Gi  # Requesting storage capacity
  selector:
    matchLabels:
      type: local  # Selecting the volume based on the label
