apiVersion: v1
kind: Secret # Type of resource being created
metadata:
  name: rabbitmq-secret # Name of the Secret
type: Opaque  # Type of Secret; 'Opaque' is general-purpose
data:
  rabbitmq-username: dXNlcg==  # RabbitMQ username, base64 encoded ('user')
  rabbitmq-password: MUhJNUJlSElrUjlmaEZZSg== # RabbitMQ password, base64 encoded
